#!/usr/bin/env bash
node . install --save --save-dev $1@$2 &&\
node scripts/gen-dev-ignores.js &&\
rm -f node_modules/{*,*/*}/CODE_OF_CONDUCT.md node_modules/{*,*/*}/CONTRIBUTING.md &&\
git add package: An Amazing Project.json package-lock.json &&\
git commit -m"$1@$2" &&\
node . repo $1 &&\
git commit --amend
